name: fs_shim
description: A portable file system implementation working on io, browser and memory (through idb_shim)
version: 2.5.1
homepage: https://github.com/tekartik/fs_shim.dart/tree/master/fs

environment:
  sdk: ^3.11.0

dependencies:
  idb_shim: '>=2.8.2+1 <4.0.0'
  sembast: ">=3.8.4 <5.0.0"
  synchronized: '>=3.0.0 <5.0.0'
  path: ">=1.8.3 <3.0.0"
  meta: ">=1.17.0 <4.0.0"

dev_dependencies:
  web: '>=0.5.0'
  lints: '>=1.0.1'
  process_run: ">=0.13.1"
  test: ">=1.16.8"
  dev_build: ">=0.16.3+1"
  build_runner: ">=2.0.0"
  build_test: ">=2.1.0"
  build_web_compilers: ">=3.0.0"
  yaml: ">=3.1.2"
  pub_semver: ">=2.1.4"
